# Generated by Django 5.2.7 on 2025-11-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField(db_index=True, verbose_name='Matrícula do Cooperado')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('data_acesso', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora do Acesso')),
            ],
            options={
                'verbose_name': 'Registro de Acesso',
                'verbose_name_plural': 'Registros de Acesso',
                'ordering': ['-data_acesso'],
            },
        ),
    ]
